name: Send Artifacts

on:
  workflow_dispatch

jobs:
  send-request:
    runs-on: windows-latest
    steps:
    - name: get-release
      id: get-release
      uses: cardinalby/git-get-release-action@1.2.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        latest: true
      
    - name: send-request
      uses: fjogeleit/http-request-action@v1.16.2
      with:
        url: 'http://127.0.0.1:3002/api/artifacts/update'
        method: 'POST'
        customHeaders: '{"Content-Type: "application/json"}'
        data: '{"secret":"${{GUVAM_SECRET}}", "assets":"${{steps.get-release.outputs.assets}}", "version":"${{steps.get-release.outputs.tag_name}}"}'
